// <auto-generated />
using System;
using CarRentalServiceAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalServiceAPI.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    partial class CarRentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarRentalServiceAPI.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RentalEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleLicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingNumber");

                    b.HasIndex("VehicleLicensePlateNumber");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingNumber = new Guid("1dad719a-a576-44cc-a8c2-d91df6a350ba"),
                            Active = true,
                            CustomerNumber = "860919-1666",
                            RentalEndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalStartTime = new DateTime(2023, 5, 12, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            VehicleLicensePlateNumber = "KHU876"
                        },
                        new
                        {
                            BookingNumber = new Guid("1b0acbe9-8c5c-47b7-93dc-3ad7809fcc2b"),
                            Active = true,
                            CustomerNumber = "440712-5621",
                            RentalEndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalStartTime = new DateTime(2023, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleLicensePlateNumber = "PLD982"
                        });
                });

            modelBuilder.Entity("CarRentalServiceAPI.Models.Vehicle", b =>
                {
                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicensePlateNumber");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            LicensePlateNumber = "ABC123",
                            Available = true,
                            Mileage = 213456,
                            Type = "Småbil"
                        },
                        new
                        {
                            LicensePlateNumber = "MPK459",
                            Available = true,
                            Mileage = 679865,
                            Type = "Småbil"
                        },
                        new
                        {
                            LicensePlateNumber = "NNE867",
                            Available = true,
                            Mileage = 238976,
                            Type = "Småbil"
                        },
                        new
                        {
                            LicensePlateNumber = "JML707",
                            Available = true,
                            Mileage = 2134567,
                            Type = "Kombi"
                        },
                        new
                        {
                            LicensePlateNumber = "KHU876",
                            Available = false,
                            Mileage = 65789,
                            Type = "Kombi"
                        },
                        new
                        {
                            LicensePlateNumber = "UYE987",
                            Available = true,
                            Mileage = 760898,
                            Type = "Kombi"
                        },
                        new
                        {
                            LicensePlateNumber = "WWO098",
                            Available = true,
                            Mileage = 6751099,
                            Type = "Kombi"
                        },
                        new
                        {
                            LicensePlateNumber = "PLD982",
                            Available = false,
                            Mileage = 98624,
                            Type = "Lastbil"
                        },
                        new
                        {
                            LicensePlateNumber = "MJD291",
                            Available = true,
                            Mileage = 6543210,
                            Type = "Lastbil"
                        });
                });

            modelBuilder.Entity("CarRentalServiceAPI.Models.Booking", b =>
                {
                    b.HasOne("CarRentalServiceAPI.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleLicensePlateNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
